imagecrop_overview:
    path:     /{_locale}/overview/{style}/{id}/{fqcn}/
    defaults: { _controller: ImageCropBundle:Default:overview }

imagecrop_crop:
    path:     /{_locale}/crop/{style}/{id}/{fqcn}/
    defaults: { _controller: ImageCropBundle:Default:crop }

imagecrop_generate_image:
    path:     /{_locale}/generate_image
    defaults: { _controller: ImageCropBundle:Default:generateTempImage }
